certificates/urls.py
from django.urls import path

from . import views

app_name = "certificates"
urlpatterns = [
    path("", views.index, name="index"), 
    path("search", views.search, name="search"),
    path("download/<str:date>/<str:name>/<str:graduation>/<str:id>", views.download, name="download"),
    path("sendrequest", views.sendrequest, name="sendrequest")
]

nfdp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include("certificates.urls"))
]

certificates/models.py
from django.db import models
from django.contrib import admin
from django.core.validators import MinLengthValidator, int_list_validator
# Create your models here.

class Fellow(models.Model):
    name = models.CharField(max_length=64)
    CNIC = models.CharField(max_length=13, 
        validators=[int_list_validator(sep=''),MinLengthValidator(13),])
    program = models.CharField(max_length=30)
    ID =  models.CharField(max_length=5)
    graduation = models.CharField(max_length=25)
    def __str__(self):
        return f"{self.name}"

class FellowAdmin (admin.ModelAdmin):
    list_display = ('name', 'CNIC', 'program', 'ID', 'graduation')
    search_fields = ('name', 'CNIC', 'program', 'ID', 'graduation',)
    filter_horizontal = ()
    list_filter = ()
    fieldsets = ()

certificates/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django import forms
from .models import Fellow
from PIL import Image, ImageDraw, ImageFont
from django.core.mail import send_mail
from django.core.validators import EmailValidator
from django.http import JsonResponse
from django.core import serializers
import os, json
# Create your views here.

class SearchForm(forms.Form):
    cnic = forms.IntegerField(label="CNIC Number", 
    widget=forms.TextInput(attrs={'placeholder': 'CNIC (without dashes)',
    'maxlength': '13', 
    'minlength': '13',
    "class": "form-control",
    'id': "cnicfield"}))

def index (request):
    search = SearchForm()
    form2 = TranscriptForm()
    return render (request, "certificates/index.html", {
            "form": search,
            'form2': form2
        }) 

def search (request):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)
    
    data = json.loads(request.body)
    cnic = data.get("cnic", "")
    if Fellow.objects.filter(CNIC=cnic):
        fellow = Fellow.objects.filter(CNIC=cnic)
        fellow = serializers.serialize('json', fellow)
        return JsonResponse(fellow, status=201, safe=False)
    else: 
        return JsonResponse({
                "error": f"Fellow with CNIC ({cnic}) does not exist."
            }, status=400)
    
    
def success (request, fellow): 
    name = fellow.name.title()
    program = fellow.program
    cnic = fellow.CNIC
    ID = fellow.ID 
    graduation = fellow.graduation
    cnic_x = fellow.CNIC[:5]+ "-" + fellow.CNIC[5:12] + "-" + fellow.CNIC [-1]
    if "Dr." not in name: name = "Dr. " + name
    return render(request, "certificates/verified.html", {
        "graduation": graduation,
        "fellow": fellow, 
        "cnic": cnic,
        "message": f"It is verified that {name} (CNIC # {cnic_x}) has successfully completed NFDP training held during {program}.",
        "email": f"To request the transcript or to verify the authenticity of the certificate, please e-mail <nahe.support@hec.gov.pk>. The certificate ID is: {ID}."
    })


def download (request, date, name, graduation, id):
    if "Dr." not in name: 
        name = f"Dr. {name}"
    date = date.split(" ")
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if graduation == "Completed Successfully":
        path = os.path.join(BASE_DIR, "certificates/static/certificates/aX201a0.jpg")
    else:
        path = os.path.join(BASE_DIR, "certificates/static/certificates/xv135gV.jpg") 

    date = f"29-{date[3]}-{date[4][:2]}" 
    image = Image.open(path)
    draw = ImageDraw.Draw(image)
    path = os.path.join(BASE_DIR, "certificates/static/certificates/ITCEDSCR.TTF")
    bounding_box = [600, 745, 1460, 800]
    x1, y1, x2, y2 = bounding_box
    font_type = ImageFont.truetype(path, 90)
    w, h = draw.textsize(name, font=font_type)
    x = (x2 - x1 - w)/2 + x1
    y = (y2 - y1 - h)/2 + y1
    path = os.path.join(BASE_DIR, "certificates/static/certificates/arial.ttf")
    font_type_2 = ImageFont.truetype(path, 35)  
    draw.text((x,y), name, align='center', font=font_type, fill=(0,102,0)) 
    font_type_3 = ImageFont.truetype(path, 30)
    msg = f"Cert. ID: {id}"
    draw.text (xy=(340, 1230), text=date, fill=(0,102,0), font=font_type_2)
    draw.text (xy=(1750, 1565), text=msg, fill=(0,0,0), font=font_type_3)
    path = os.path.join(BASE_DIR, f"certificates/static/certificates/{name}.pdf")
    image.save(path, "PDF", resolution=100.0)
    with open(path, 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = f'inline;filename=NFDP-{name}.pdf'
        return response

emailvalidator = EmailValidator(message="invalid email")
class TranscriptForm(forms.Form):
    name = forms.CharField(label="Name", 
    widget=forms.TextInput(attrs={
        'placeholder': 'full name',
        'max_length': '64',
        "class": "form-control",
        "id": "t-name"
        }))
    
    organization = forms.CharField(label="Organization", 
    widget=forms.TextInput(attrs={
        'placeholder': 'name of organization/institute',
        'max_length': '64',
        "class": "form-control",
        "id": "organization"}))
    title = forms.CharField(label="Employment Title", 
    widget=forms.TextInput(attrs={
        'placeholder': 'position title',
        'max_length': '64',
        "id": 'title',
        "class": "form-control"}))
    message = forms.CharField(label="Message", 
    widget=forms.Textarea(attrs={
        'placeholder': 'Please provide a short description about why you want to request the transcript.',
        "class": "form-control",
        "id": 'message'}
    ))
    email = forms.CharField(validators=[emailvalidator], widget=forms.TextInput(attrs={
        'placeholder': 'valid official email address',
        "class": "form-control",
        "id": 'email'}
    ))


def sendrequest (request):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)
    
    data = json.loads(request.body)
    cnic = data.get("cnic", "")
    name = data.get("name", "")
    organization = data.get("org", "")
    email = data.get("email", "")
    title = data.get("title", "")
    msg = data.get("msg", "")


    if Fellow.objects.filter(CNIC=cnic):
        fellow = Fellow.objects.get(CNIC=cnic)
        message = f"""A requested for transcript has been generated by:\n\n
            Name: {name.title()}
            Organization: {organization.title()}
            Title: {title.title()}
            Email: {email}
            Message: \n{msg}\n
            This request has been generated for the following NFDP fellow:\n
            Fellow: {fellow.name}
            Program: {fellow.program}
            Cert. ID: {fellow.ID}
            CNIC: {cnic}\n
            THIS IS AN AUTO-GENERATED EMAIL. DO NOT REPLY."""
        emails = ['nahe.support@hec.gov.pk', email]
        try:
            for i in emails:
                send_mail('Transcript Request for NFDP Fellow',
                message,
                None,
                [i],
                fail_silently=False)
            return JsonResponse({"status": 'success'}, status=201, safe=False)
        except: 
            return JsonResponse({"status": 'fail'}, status=400) 
   

certificates/templates/certificates/index.html
{% extends "certificates/layout.html" %}
{% load static %}
{% block title %}
    Verify Certificates
{% endblock %}

{% block body %}
    <div id="transcripts">
        <div class="alert alert-info" role="alert" style="font-size: 17.5px">
            Please fill the form completely in order to request the transcript. If you are unable
            to fill the form, please email 'nahe.support@hec.gov.pk' to request the transcript.
            Make sure to please provide the fellow's name, CNIC, certificate ID along with your name,
            organization, employment title, and email address. 
        </div>
        <div style= "font-size: 20px; margin-top: -30px;" class="alert alert-danger" role="alert">
            Transcript requests will ONLY be processed for institutions and/or organizations.
            Any request made by the NFDP participant and/or IPFP fellow will NOT be facilitated.
        </div><br>
        <center>
        <div class="col-6" style= "margin-top: -17px; background-color: bisque;">
            <div class="form-group ">
                <form id="form2">
                    {% csrf_token %}
                    {{ form2.as_table }}<br>
                    <input class="btn btn-primary" type="submit"/>
                </form>
    
            </div>
        </div>
        </center>
    </div>
    <div id="verified">
        <div class="row">
            <div class="col-10">
              <div id="note" class="row alert alert-success" role="alert"></div>
              <div style= "background-color: beige;" class="row">
                <div class="col-2">
                  <div class="list-group" id="list-tab" role="tablist">
                    <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Name</a>
                    <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Certificate ID</a>
                    <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">NFDP Program</a>
                  </div>
                </div>
                <div class="col-5">
                  <div class="tab-content" id="nav-tabContent">
                    <div style= "font-size: 25px" class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list"></div>
                    <div style= "font-size: 25px" class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list"></div>
                    <div style= "font-size: 25px" class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list"></div>
                
                  </div>
                </div>
              </div>
            </div>
            <div class="col-2" style="background-color: beige; margin: auto;">
              <div>
                  <ul class="nav nav-pills nav-fill">
                    <br><br>
                    <li class="nav-item">
                        <a style="color: white;" id="search-again" class="btn btn-primary">Search Again</a>
                    </li><br><br>
                    <li class="nav-item">
                        <a style="color: white;" id="download" class="btn btn-primary" download>Download Certificate</a>
                    </li><br><br>
                    <li class="nav-item">
                      <a style="color: white;" id="transcript" class="btn btn-primary">Request Transcript</a>
                    </li> 
                  </ul>
              </div>
            </div>
        </div>
    </div>

    <div id="fail" style= "font-size: 20px" class="alert alert-danger" role="alert"></div>

    <div id="home">
        <div class="alert alert-info" role="alert" style="font-size: 17.5px">
            Please enter the 13-digit Computerized National Identity Card (CNIC) number to 
            verify the successful completion of the National Faculty Development Program (NFDP)
            by the fellow. This online verification system serves as an electronic attestation by the
            National Academy of Higher Education (NAHE). 
        </div>
        <div class="form-group">
            <!-- action="{% url 'certificates:index' %}" -->
            <form id="search">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary"/>
            </form>
        </div>

    </div>

{% endblock %}

{% block script %}
<script src="{% static 'certificates/views.js' %}"></script>
{% endblock %}

certificates/templates/certificates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'certificates/styles.css' %}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </head>
    <div>
        <img src="{% static 'certificates/NFDP2020.jpg' %}">
    </div>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>